name: VITE MPA Publicar a Github Pages

#Cuando se dispara (cuando se hace un push) se dice con on
#probando

on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
#VARIABLES DE AMBIENTE
env:
  DEPLOY_BASE_URL: ${{ vars.DEPLOY_BASE_URL}} 
concurrency:
  group: "pages"
  cancel-in-progress: true

#hasta aqui solo se ha programado el entorno
#de aqui para abajo, lo que se va a hacer

#NOTA: no instalar el github CLI. Puras acciones de GitHub

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.github-pages.output.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el Repositorio
        uses: actions/checkout@v4
      - name: Instalar Nodejs
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Instalar Dependencias del Proyecto
        run: npm install
      - name: Compilar el Proyecto en Dist
        run: npm run build
      - name: Configurar Github Pages para Publicar
        uses: actions/configure-pages@v5
      - name: Subir los Compilados (DIST)
        uses: actions/upload-pages-artifact@v4
        with:
          path: './dist'
      - name: Publicar Artefactos
        uses: actions/deploy-pages@v4